import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Notice = { id: string; title: string; body: string; status: 'draft' | 'published'; createdAt: string; publishedAt: string | null };
type Page = 'home' | 'about' | 'academics' | 'admissions' | 'campus' | 'contact' | 'admin';
const programs = [
  { name: 'Engineering & Technology', image: '/assets/3.jpg', detail: 'Explore technical disciplines, laboratories and project based learning.' },
  { name: 'Business & Commerce', image: '/assets/4.jpg', detail: 'Develop analytical, management and entrepreneurial skills.' },
  { name: 'Arts & Sciences', image: '/assets/5.jpg', detail: 'Build a foundation for research, creativity and critical inquiry.' }
];
const pages: { id: Page; label: string }[] = [
  { id: 'home', label: 'Home' }, { id: 'about', label: 'About' }, { id: 'academics', label: 'Academics' }, { id: 'admissions', label: 'Admissions' }, { id: 'campus', label: 'Campus life' }, { id: 'contact', label: 'Contact' }
];
async function api<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, ...options });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Request failed');
  return data;
}
function App() {
  const [page, setPage] = useState<Page>('home');
  const [menuOpen, setMenuOpen] = useState(false);
  const [notices, setNotices] = useState<Notice[]>([]);
  const [noticeError, setNoticeError] = useState('');
  const [admin, setAdmin] = useState(false);
  const [adminNotices, setAdminNotices] = useState<Notice[]>([]);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');
  const [message, setMessage] = useState('');
  useEffect(() => { api<Notice[]>('/api/notices').then(setNotices).catch(() => setNoticeError('Notices are temporarily unavailable.')); api('/api/me').then(() => setAdmin(true)).catch(() => {}); }, []);
  useEffect(() => { if (admin) api<Notice[]>('/api/admin/notices').then(setAdminNotices).catch(() => setAdmin(false)); }, [admin]);
  const navigate = (next: Page) => { setPage(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const refresh = async () => { setAdminNotices(await api<Notice[]>('/api/admin/notices')); setNotices(await api<Notice[]>('/api/notices')); };
  const login = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); try { await api('/api/login', { method: 'POST', body: JSON.stringify({ email, password }) }); setPassword(''); setAdmin(true); setMessage('Signed in.'); } catch (error) { setMessage((error as Error).message); } };
  const createNotice = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); try { await api('/api/admin/notices', { method: 'POST', body: JSON.stringify({ title, body }) }); setTitle(''); setBody(''); await refresh(); setMessage('Draft saved.'); } catch (error) { setMessage((error as Error).message); } };
  const publish = async (id: string) => { setMessage(''); try { await api(`/api/admin/notices/${id}/publish`, { method: 'POST' }); await refresh(); setMessage('Notice published.'); } catch (error) { setMessage((error as Error).message); } };
  const logout = async () => { await api('/api/logout', { method: 'POST' }); setAdmin(false); setAdminNotices([]); setMessage('Signed out.'); };
  return <>
    <a className="skip" href="#main">Skip to content</a>
    <div className="topbar"><div className="wrap topbar-inner"><span>College website preview · Institutional details pending</span><button onClick={() => navigate('admin')}>Admin portal →</button></div></div>
    <header className="site-header"><div className="wrap header-inner"><button className="brand" onClick={() => navigate('home')} aria-label="College home"><span className="brand-mark">C</span><span><strong>Your College</strong><small>Learn · Discover · Grow</small></span></button><button className="menu-toggle" aria-expanded={menuOpen} aria-controls="main-nav" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? 'Close' : 'Menu'}</button><nav id="main-nav" className={menuOpen ? 'open' : ''} aria-label="Main navigation">{pages.map(item => <button key={item.id} className={page === item.id ? 'active' : ''} onClick={() => navigate(item.id)}>{item.label}</button>)}</nav><button className="header-cta" onClick={() => navigate('admissions')}>Apply now <span aria-hidden="true">↗</span></button></div></header>
    <main id="main">
      {page === 'home' && <><section className="hero"><div className="hero-image"/><div className="wrap hero-content"><span className="eyebrow light">A place to begin what comes next</span><h1>Make room for<br/><em>what’s possible.</em></h1><p>Explore programs, find your community and take your next step with confidence.</p><div className="hero-actions"><button className="button button-light" onClick={() => navigate('academics')}>Explore programs <span>→</span></button><button className="text-button" onClick={() => navigate('admissions')}>How to apply <span>→</span></button></div></div><div className="hero-caption">Illustrative image from the supplied template</div></section><section className="intro wrap"><div><span className="eyebrow">Welcome</span><h2>Education that opens doors.</h2></div><p>Find the path that fits your ambitions. Browse academic opportunities, learn about admissions and stay connected to campus updates. Verified institutional information will be added here before launch.</p></section><section className="program-section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">Academics</span><h2>Find your direction</h2></div><button className="link-button" onClick={() => navigate('academics')}>View all programs <span>→</span></button></div><div className="program-grid">{programs.map((p, i) => <button className="program-card" key={p.name} onClick={() => navigate('academics')}><img src={p.image} alt=""/><div><span>0{i + 1} / Study area</span><h3>{p.name}</h3><span className="card-arrow">↗</span></div></button>)}</div></div></section><section className="split-section wrap"><img src="/assets/h-adm.jpg" alt="Students meeting on campus"/><div><span className="eyebrow">Admissions</span><h2>Your next chapter starts here.</h2><p>Understand the application process, prepare your documents and find the right people to help you along the way.</p><button className="button button-dark" onClick={() => navigate('admissions')}>Admissions guide <span>→</span></button></div></section><section className="notice-section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">Stay informed</span><h2>Latest notices</h2></div></div><NoticeList notices={notices} error={noticeError}/></div></section></>}
      {page === 'about' && <PageLayout eyebrow="Our story" title="About the college" image="/assets/h-about.jpg"><p>Our mission, leadership, accreditations, history and mandatory disclosures will be published here after the college confirms its official details.</p><div className="info-grid"><Info title="Vision & mission" text="A clear statement of the institution’s purpose and long term direction."/><Info title="Governance" text="Leadership, policies and statutory information in one accessible place."/><Info title="Campus" text="An environment for learning, collaboration and personal growth."/></div></PageLayout>}
      {page === 'academics' && <PageLayout eyebrow="Academic life" title="Explore academics" image="/assets/course.jpg"><p>Browse study areas below. Approved department, program and course details, including eligibility and curriculum, will be added to the catalog.</p><div className="info-grid">{programs.map(p => <Info key={p.name} title={p.name} text={p.detail}/>)}</div></PageLayout>}
      {page === 'admissions' && <PageLayout eyebrow="Join us" title="Admissions" image="/assets/h-adm.jpg"><p>Application dates, eligibility, intake, fees and required documents need confirmation from the college. The application workflow is a planned next development slice.</p><div className="steps"><Info title="01 · Explore" text="Review the approved programs and admission criteria."/><Info title="02 · Prepare" text="Gather documents and review important dates."/><Info title="03 · Apply" text="Submit an application and track its progress when admissions open."/></div><button className="button button-dark" onClick={() => navigate('contact')}>Ask a question <span>→</span></button></PageLayout>}
      {page === 'campus' && <PageLayout eyebrow="Beyond the classroom" title="Campus life" image="/assets/h-cam.jpg"><p>Discover spaces and experiences that support study, wellbeing and community. Details about facilities, events, clubs and services will be verified before publication.</p><div className="info-grid"><Info title="Facilities" text="Learning spaces and campus services."/><Info title="Events" text="Academic and community activities."/><Info title="Student support" text="Guidance, accessibility and wellbeing resources."/></div></PageLayout>}
      {page === 'contact' && <PageLayout eyebrow="Get in touch" title="Contact us" image="/assets/2.jpg"><p>Official address, phone, email and office hours are awaiting confirmation. The enquiry form will be connected to the service queue in the next phase.</p><div className="contact-box"><h3>Contact details pending</h3><p>Please add verified college contact information before publishing this page.</p></div></PageLayout>}
      {page === 'admin' && <section className="admin-page wrap"><span className="eyebrow">Content management</span><h1>Notice desk</h1><p className="admin-intro">Create a draft, review it, then publish it to the public site.</p>{message && <div className="message" role="status">{message}</div>}{!admin ? <form className="form-card" onSubmit={login}><h2>Admin sign in</h2><label>Email<input type="email" required autoComplete="username" value={email} onChange={e => setEmail(e.target.value)}/></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)}/></label><button className="button button-dark" type="submit">Sign in <span>→</span></button><p>Set ADMIN_EMAIL and ADMIN_PASSWORD on the API server to enable this account.</p></form> : <div className="admin-layout"><form className="form-card" onSubmit={createNotice}><h2>New notice</h2><label>Title<input required minLength={5} maxLength={160} value={title} onChange={e => setTitle(e.target.value)}/></label><label>Body<textarea required minLength={10} maxLength={5000} rows={7} value={body} onChange={e => setBody(e.target.value)}/></label><button className="button button-dark" type="submit">Save draft <span>→</span></button></form><div className="admin-list"><div className="admin-list-head"><h2>All notices</h2><button className="link-button" onClick={logout}>Sign out</button></div>{adminNotices.length === 0 && <p>No notices yet.</p>}{adminNotices.map(n => <article className="admin-notice" key={n.id}><span className={`badge ${n.status}`}>{n.status}</span><h3>{n.title}</h3><p>{n.body}</p>{n.status === 'draft' && <button className="button button-outline" onClick={() => publish(n.id)}>Publish notice →</button>}</article>)}</div></div>}</section>}
    </main><footer><div className="wrap footer-grid"><div><div className="footer-brand">Your College</div><p>A foundation for what comes next.</p><small>Institutional identity and contact details pending verification.</small></div><div><h3>Explore</h3>{pages.slice(1, 4).map(p => <button key={p.id} onClick={() => navigate(p.id)}>{p.label}</button>)}</div><div><h3>Connect</h3>{pages.slice(4).map(p => <button key={p.id} onClick={() => navigate(p.id)}>{p.label}</button>)}</div></div><div className="wrap footer-bottom">© {new Date().getFullYear()} Your College · Website preview</div></footer>
  </>;
}
function NoticeList({ notices, error }: { notices: Notice[]; error: string }) { return <div className="notices">{error ? <p role="status">{error}</p> : notices.length === 0 ? <p>No notices published yet.</p> : notices.map(n => <article key={n.id} className="notice"><span>{n.publishedAt ? new Date(n.publishedAt).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : ''}</span><div><h3>{n.title}</h3><p>{n.body}</p></div><span aria-hidden="true">↗</span></article>)}</div> }
function PageLayout({ eyebrow, title, image, children }: { eyebrow: string; title: string; image: string; children: React.ReactNode }) { return <><section className="page-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(18,46,58,.86), rgba(18,46,58,.22)), url('${image}')` }}><div className="wrap"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1></div></section><section className="page-content wrap">{children}</section></> }
function Info({ title, text }: { title: string; text: string }) { return <article className="info-card"><h3>{title}</h3><p>{text}</p></article> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
